name: Deploy Next.js to Production

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci

      - name: Build static site Next.js application
        run: npm run build

      - name: Deploy via SCP
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "out/*"
          target: "/home/${{ secrets.SSH_USERNAME }}/temp-site"

      - name: Move to /var/www/main with sudo
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            sudo rm -rf /var/www/main/*
            sudo cp -r /home/${{ secrets.SSH_USERNAME }}/temp-site/out/* /var/www/main/
            rm -rf /home/${{ secrets.SSH_USERNAME }}/temp-site
            sudo chmod -R 755 /var/www/main
            sudo chown -R www-data:www-data /var/www/main
            echo "Deployment complete!"
